(function(){
  window.extraGames=window.extraGames||{};
  function by(id){return document.getElementById(id)}
  function setupCanvas(id,w,h){var c=by(id);if(!c)return [null,null];c.width=w;c.height=h;return [c,c.getContext('2d')]}
  function keysFor(view){var k={};document.addEventListener('keydown',function(e){var v=by('view-'+view);if(!v||!v.classList.contains('active'))return;k[e.code]=true;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space','KeyW','KeyA','KeyS','KeyD','Enter','KeyF'].indexOf(e.code)>=0)e.preventDefault();});document.addEventListener('keyup',function(e){k[e.code]=false});return k}
  function rafGame(loop){var id=0,last=performance.now();function f(t){var dt=Math.min(.035,(t-last)/1000);last=t;loop(dt,t);id=requestAnimationFrame(f)}id=requestAnimationFrame(f);return function(){cancelAnimationFrame(id)}}
  var confirmReset=window.confirmReset||function(fn){fn()};
  window.extraGames.airhockey=function(){var a=setupCanvas('air-canvas',640,400),c=a[0],x=a[1],k=keysFor('airhockey'),mode='cpu',p=[200,200],q=[200,200],puck,sc=[0,0],raf;function reset(){p=[200,200];q=[200,200];puck={x:320,y:200,vx:260*(Math.random()<.5?-1:1),vy:80};sc=[0,0];hud();if(raf)raf();raf=rafGame(loop)}function loop(dt){var s=300;p[1]+=((k.KeyS?1:0)-(k.KeyW?1:0))*s*dt;q[1]+=((k.ArrowDown?1:0)-(k.ArrowUp?1:0))*s*dt;if(mode==='cpu')q[1]+=Math.sign(puck.y-q[1])*180*dt;p[1]=Math.max(45,Math.min(355,p[1]));q[1]=Math.max(45,Math.min(355,q[1]));puck.x+=puck.vx*dt;puck.y+=puck.vy*dt;if(puck.y<10||puck.y>390)puck.vy*=-1;if(puck.x<30&&Math.abs(puck.y-p[1])<55&&puck.vx<0){puck.vx=Math.abs(puck.vx)*1.04;puck.vy+=(puck.y-p[1])*2}if(puck.x>610&&Math.abs(puck.y-q[1])<55&&puck.vx>0){puck.vx=-Math.abs(puck.vx)*1.04;puck.vy+=(puck.y-q[1])*2}if(puck.x<0){sc[1]++;serve(1)}if(puck.x>640){sc[0]++;serve(-1)}hud();draw();if(sc[0]>=7||sc[1]>=7){by('air-msg').textContent=(sc[0]>sc[1]?'You win!':'Opponent wins!');if(window.saveGameHubScore)window.saveGameHubScore('airhockey',sc[0]*10)}}function serve(d){puck={x:320,y:200,vx:d*260,vy:80*(Math.random()>.5?1:-1)}}function hud(){by('air-p1').textContent=sc[0];by('air-p2').textContent=sc[1]}function draw(){x.fillStyle='#dceef2';x.fillRect(0,0,640,400);x.strokeStyle='#fff';x.lineWidth=4;x.strokeRect(8,8,624,384);x.beginPath();x.moveTo(320,0);x.lineTo(320,400);x.stroke();x.fillStyle='#4f8cff';x.beginPath();x.arc(25,p[1],35,0,7);x.fill();x.fillStyle='#e05a5a';x.beginPath();x.arc(615,q[1],35,0,7);x.fill();x.fillStyle='#111';x.beginPath();x.arc(puck.x,puck.y,12,0,7);x.fill()}reset();document.querySelectorAll('[data-air]').forEach(b=>b.onclick=function(){mode=b.dataset.air;document.querySelectorAll('[data-air]').forEach(z=>z.classList.toggle('active',z===b));reset()});by('air-new').onclick=function(){confirmReset(reset)}};
})();
