window.extraGames=window.extraGames||{};window.extraGames.basket=function(){
  function by(id){return document.getElementById(id)}
  function setup(id,w,h){var c=by(id);if(!c)return null;c.width=w;c.height=h;return[c,c.getContext('2d')]}
  function keys(){var k={};document.addEventListener('keydown',function(e){var v=by('view-basket');if(!v||!v.classList.contains('active'))return;k[e.code]=true;if(['ArrowLeft','ArrowRight','ArrowUp','Space','KeyA','KeyD','KeyW'].indexOf(e.code)>=0)e.preventDefault()});document.addEventListener('keyup',function(e){k[e.code]=false});return k}
  var a=setup('br-canvas',720,420);if(!a)return;var c=a[0],x=a[1],k=keys();var W=720,H=420,FLOOR=H-40,mode='cpu',p1=0,p2=0,raf,over=false;var ball,pL,pR,grav,rest,jumpPow,hue;
  function stop(){if(raf){cancelAnimationFrame(raf);raf=0}}
  function reset(full){if(full){p1=0;p2=0}stop();over=false;grav=1500;rest=.68;jumpPow=650;hue=Math.floor(Math.random()*360);ball={x:W/2,y:120,vx:(Math.random()<.5?-1:1)*220,vy:0,r:13,prevY:120};pL={x:180,y:FLOOR-30,vy:0,r:24};pR={x:540,y:FLOOR-30,vy:0,r:24};by('br-p1').textContent=p1;by('br-p2').textContent=p2;by('br-msg').textContent='P1: A/D + W · '+(mode==='cpu'?'Computer moves automatically.':'P2: ←/→ + ↑') ;raf=requestAnimationFrame(loop)}
  function jump(p){if(p.y>=FLOOR-31){p.vy=-jumpPow}}
  function movePlayer(p,left,right,dt){var dx=(right?1:0)-(left?1:0);p.x=Math.max(45,Math.min(W-45,p.x+dx*260*dt))}
  function checkHoop(hx){if(over)return;if(ball.prevY<150&&ball.y>=150&&Math.abs(ball.x-hx)<20&&ball.vy>0){if(hx<360)p2++;else p1++;by('br-p1').textContent=p1;by('br-p2').textContent=p2;var win=p1>=5||p2>=5;over=true;by('br-msg').textContent=win?(p1>p2?'🏆 P1 wins!':'🏆 P2 wins!'):'Score! Next round…';if(!win)setTimeout(function(){var v=by('view-basket');if(v&&v.classList.contains('active'))reset(false)},700)}}
  function loop(t){var dt=Math.min(.035,(t-(loop.last||t))/1000);loop.last=t;if(over){draw();raf=requestAnimationFrame(loop);return}movePlayer(pL,k.KeyA,k.KeyD,dt);if(mode==='2p')movePlayer(pR,k.ArrowLeft,k.ArrowRight,dt);else{var dir=ball.x>pR.x?1:-1;if(Math.abs(ball.x-pR.x)>18)pR.x+=dir*190*dt;if(ball.x>pR.x-20&&ball.x<pR.x+20&&ball.y<230)jump(pR)}if(k.KeyW||k.Space){k.KeyW=false;k.Space=false;jump(pL)}if(mode==='2p'&&k.ArrowUp){k.ArrowUp=false;jump(pR)}[pL,pR].forEach(function(p){p.vy+=grav*dt;p.y+=p.vy*dt;if(p.y>FLOOR-30){p.y=FLOOR-30;p.vy=0}});ball.vy+=grav*dt;ball.prevY=ball.y;ball.x+=ball.vx*dt;ball.y+=ball.vy*dt;if(ball.x<ball.r){ball.x=ball.r;ball.vx=Math.abs(ball.vx)*rest}if(ball.x>W-ball.r){ball.x=W-ball.r;ball.vx=-Math.abs(ball.vx)*rest}if(ball.y>FLOOR-ball.r){ball.y=FLOOR-ball.r;ball.vy=-Math.abs(ball.vy)*rest;ball.vx*=.97}if(ball.y<ball.r){ball.y=ball.r;ball.vy=Math.abs(ball.vy)*rest}[pL,pR].forEach(function(p){var dx=ball.x-p.x,dy=ball.y-(p.y-6),d=Math.hypot(dx,dy)||1;if(d<ball.r+p.r){var nx=dx/d,ny=dy/d,sp=Math.max(Math.hypot(ball.vx,ball.vy),320);ball.vx=nx*sp;ball.vy=ny*sp-80;ball.x=p.x+nx*(ball.r+p.r+1);ball.y=p.y-6+ny*(ball.r+p.r+1)}});checkHoop(72);checkHoop(648);draw();raf=requestAnimationFrame(loop)}
  function draw(){x.fillStyle='hsl('+hue+',45%,12%)';x.fillRect(0,0,W,H);x.fillStyle='hsl('+hue+',30%,22%)';x.fillRect(0,FLOOR,W,40);[72,648].forEach(function(hx){x.fillStyle='#e8e8e8';x.fillRect(hx<360?hx-30:hx+18,90,12,70);x.strokeStyle='#e8533a';x.lineWidth=4;x.beginPath();x.moveTo(hx-20,150);x.lineTo(hx+20,150);x.stroke()});function player(p,col){x.fillStyle=col;x.beginPath();x.arc(p.x,p.y,p.r,0,7);x.fill();x.fillRect(p.x-10,p.y,20,30)}player(pL,'#4f9cf0');player(pR,'#f07050');x.fillStyle='#e8913a';x.beginPath();x.arc(ball.x,ball.y,ball.r,0,7);x.fill()}
  c.addEventListener('pointerdown',function(e){var r=c.getBoundingClientRect(),mx=(e.clientX-r.left)*W/r.width;if(mx<W/2)jump(pL);else jump(pR)});document.querySelectorAll('[data-br]').forEach(function(b){b.onclick=function(e){e.preventDefault();mode=b.dataset.br;document.querySelectorAll('[data-br]').forEach(function(z){z.classList.toggle('active',z===b)});reset(true)}});by('br-new').onclick=function(){reset(true)};reset(true);
};
