window.extraGames=window.extraGames||{};window.extraGames.bitlife=function(){
var st,logEl,choicesEl,statsEl,ageEl,msgEl;var NAMES=['Alex','Sam','Jordan','Taylor','Casey','Riley','Morgan','Jamie','Avery','Quinn'];
function by(id){return document.getElementById(id)}
function reset(){st={name:NAMES[Math.floor(Math.random()*NAMES.length)],age:0,stats:{hap:80,hea:85,sma:50,lok:60},money:0,job:'',partner:'',club:'',alive:true,pending:null};logEl.innerHTML='';render();pushLog('You were born.');msgEl.textContent='Tap Age +1 to live your life.'}
function pushLog(t){var e=document.createElement('div');e.className='bl-entry';e.textContent='Age '+st.age+': '+t;logEl.insertBefore(e,logEl.firstChild);while(logEl.childNodes.length>30)logEl.removeChild(logEl.lastChild)}
function render(){by('bl-name').textContent=st.name;ageEl.textContent='Age '+st.age;var s=st.stats;var rows=[['Happiness',s.hap,'hap'],['Health',s.hea,'hea'],['Smarts',s.sma,'sma'],['Looks',s.lok,'lok']];statsEl.innerHTML='';rows.forEach(function(r){var d=document.createElement('div');d.className='bl-stat';d.innerHTML='<b>'+r[0]+': '+Math.round(r[1])+'</b><div class="bl-bar '+r[2]+'"><i style="width:'+Math.max(0,Math.min(100,r[1]))+'%"></i></div>';statsEl.appendChild(d)});var md=document.createElement('div');md.className='bl-stat';md.innerHTML='<b>Money: $'+st.money+'</b>'+(st.job?' · '+st.job:'')+(st.club?' · Club: '+st.club:'');statsEl.appendChild(md)}
function setChoices(list){choicesEl.innerHTML='';list.forEach(function(ch){var b=document.createElement('button');b.textContent=ch.label;b.onclick=function(){var res=ch.apply(st);if(res)pushLog(res);st.pending=null;render();msgEl.textContent='Tap Age +1 to continue.'};choicesEl.appendChild(b)})}
var EVENTS=[
{min:6,max:18,text:'Your school has clubs available. Pick one to join.',choices:[{label:'Science Club',apply:function(s){s.club='Science Club';s.stats.sma+=8;s.stats.hap+=3;return'You joined the Science Club.'}},{label:'Art Club',apply:function(s){s.club='Art Club';s.stats.hap+=7;s.stats.lok+=3;return'You joined the Art Club.'}},{label:'Sports Club',apply:function(s){s.club='Sports Club';s.stats.hea+=8;s.stats.hap+=5;return'You joined the Sports Club.'}},{label:'Drama Club',apply:function(s){s.club='Drama Club';s.stats.hap+=8;s.stats.lok+=2;return'You joined the Drama Club.'}},{label:'Skip Clubs',apply:function(s){return'You skipped clubs.'}}]},
{min:16,max:20,text:'Time to think about after high school.',choices:[{label:'Apply to college',apply:function(s){if(s.stats.sma>=55){s.stats.sma+=10;return'You got accepted to college!'}return'Your grades were too low.'}},{label:'Get a job',apply:function(s){s.job='Cashier';s.money+=4000;return'You started as a cashier.'}}]},
{min:21,max:35,text:'A friend pitches a side business.',choices:[{label:'Invest $2,000',apply:function(s){if(s.money>=2000){s.money-=2000;if(Math.random()<.5){s.money+=8000;return'The business paid off!'}return'The business failed.'}return'You did not have enough money.'}},{label:'Pass',apply:function(s){return'You played it safe.'}}]},
{min:25,max:45,text:'A recruiter offers a coding bootcamp.',choices:[{label:'Take the course ($3,000)',apply:function(s){if(s.money>=3000){s.money-=3000;s.job='Developer';s.stats.sma+=6;return'You became a developer!'}return'Not enough money.'}},{label:'Decline',apply:function(s){return'You declined.'}}]},
{min:30,max:55,text:'Your doctor suggests a healthy lifestyle change.',choices:[{label:'Start exercising',apply:function(s){s.stats.hea+=14;s.stats.hap+=4;return'You improved your health.'}},{label:'Ignore it',apply:function(s){s.stats.hea-=8;return'Your health declined.'}}]},
{min:40,max:60,text:'You receive an inheritance.',choices:[{label:'Save it',apply:function(s){s.money+=15000;return'You inherited $15,000.'}},{label:'Spend some',apply:function(s){s.money+=15000;s.stats.hap+=6;return'You inherited $15,000 and spent some.'}}]},
{min:55,max:80,text:'It is time to retire or keep working.',choices:[{label:'Retire',apply:function(s){s.job='Retired';s.stats.hap+=8;return'You retired.'}},{label:'Keep working',apply:function(s){s.money+=8000;s.stats.hea-=4;return'You kept working.'}}]}
];
function ageUp(){if(!st.alive)return;if(st.pending){msgEl.textContent='Make your choice first!';return}st.age++;if(st.age>35)st.stats.hea-=.6;if(st.age>55){st.stats.hea-=1.2;st.stats.lok-=1}if(st.age>70)st.stats.hea-=1.8;st.stats.hap-=.4;if(st.job&&st.age>=18)st.money+=st.job==='Developer'?9000:st.job==='Retired'?0:4500;if(st.age===6)pushLog('You started elementary school.');if(st.age===14)pushLog('You entered high school.');var pool=EVENTS.filter(function(e){return st.age>=e.min&&st.age<=e.max});if(pool.length&&Math.random()<.75){var ev=pool[Math.floor(Math.random()*pool.length)];if(st.club&&ev.min===6)ev=null;if(ev){st.pending=ev;setChoices(ev.choices);msgEl.textContent=ev.text;render();return}}var deathChance=st.age>60?(st.age-60)*.012:0;if(st.stats.hea<=0)deathChance=.5;if(st.age>=100||Math.random()<deathChance){die();return}pushLog('You aged to '+st.age+'.');render();msgEl.textContent='Tap Age +1 to continue.'}
function die(){st.alive=false;choicesEl.innerHTML='';pushLog('You died at age '+st.age+'.');msgEl.textContent='You died at '+st.age+'. Final worth: $'+st.money+'. Tap New Life.';var b=document.createElement('button');b.textContent='Start New Life';b.onclick=reset;choicesEl.appendChild(b)}
function init(){logEl=by('bl-log');choicesEl=by('bl-choices');statsEl=by('bl-stats');ageEl=by('bl-age');msgEl=by('bl-msg');by('bl-age-btn').onclick=ageUp;by('bl-new-btn').onclick=function(){confirmReset(reset)};reset()}init();};
