(function(){
  window.extraGames=window.extraGames||{};
  function by(id){return document.getElementById(id)}
  function setupCanvas(id,w,h){var c=by(id);if(!c)return [null,null];c.width=w;c.height=h;return [c,c.getContext('2d')]}
  function keysFor(view){var k={};document.addEventListener('keydown',function(e){var v=by('view-'+view);if(!v||!v.classList.contains('active'))return;k[e.code]=true;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space','KeyW','KeyA','KeyS','KeyD','Enter','KeyF'].indexOf(e.code)>=0)e.preventDefault();});document.addEventListener('keyup',function(e){k[e.code]=false});return k}
  function rafGame(loop){var id=0,last=performance.now();function f(t){var dt=Math.min(.035,(t-last)/1000);last=t;loop(dt,t);id=requestAnimationFrame(f)}id=requestAnimationFrame(f);return function(){cancelAnimationFrame(id)}}
  var confirmReset=window.confirmReset||function(fn){fn()};
  window.extraGames.climb=function(){var a=setupCanvas('climb-canvas',640,440),c=a[0],x=a[1],k=keysFor('climb'),p,plats,cam,best=0,raf;function reset(){p={x:320,y:380,vx:0,vy:0,on:false};plats=[];cam=0;for(var i=0;i<16;i++)plats.push({x:30+Math.random()*520,y:410-i*70,w:90,h:12});if(raf)raf();raf=rafGame(loop)}function loop(dt){var dx=(k.KeyD||k.ArrowRight?1:0)-(k.KeyA||k.ArrowLeft?1:0);p.vx+=dx*900*dt;p.vx*=.88;p.vx=Math.max(-220,Math.min(220,p.vx));p.vy+=900*dt;if((k.Space||k.KeyW)&&p.on){p.vy=-430;p.on=false}p.x=Math.max(8,Math.min(632,p.x+p.vx*dt));p.y+=p.vy*dt;p.on=false;plats.forEach(q=>{if(p.vy>0&&p.x>q.x-10&&p.x<q.x+q.w&&p.y+18>q.y&&p.y+18<q.y+q.h+12){p.y=q.y-18;p.vy=0;p.on=true}});if(p.y<180){var d=180-p.y;p.y=180;cam+=d;plats.forEach(q=>q.y+=d)}var h=Math.max(0,Math.round(cam/10));best=Math.max(best,h);by('climb-height').textContent=h;by('climb-best').textContent=best;if(p.y>450){by('climb-msg').textContent='You fell! Height: '+h;if(window.saveGameHubScore)window.saveGameHubScore('climb',best);return}draw()}function draw(){x.fillStyle='#0e1726';x.fillRect(0,0,640,440);x.fillStyle='#5b8def';plats.forEach(q=>x.fillRect(q.x,q.y,q.w,q.h));x.fillStyle='#f2c94c';x.fillRect(p.x-9,p.y,18,18)}reset();by('climb-new').onclick=function(){confirmReset(reset)}};
})();
