(function(){
  window.extraGames=window.extraGames||{};
  function by(id){return document.getElementById(id)}
  function setupCanvas(id,w,h){var c=by(id);if(!c)return [null,null];c.width=w;c.height=h;return [c,c.getContext('2d')]}
  function keysFor(view){var k={};document.addEventListener('keydown',function(e){var v=by('view-'+view);if(!v||!v.classList.contains('active'))return;k[e.code]=true;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space','KeyW','KeyA','KeyS','KeyD','Enter','KeyF'].indexOf(e.code)>=0)e.preventDefault();});document.addEventListener('keyup',function(e){k[e.code]=false});return k}
  function rafGame(loop){var id=0,last=performance.now();function f(t){var dt=Math.min(.035,(t-last)/1000);last=t;loop(dt,t);id=requestAnimationFrame(f)}id=requestAnimationFrame(f);return function(){cancelAnimationFrame(id)}}
  var confirmReset=window.confirmReset||function(fn){fn()};
  window.extraGames.coinrush=function(){var a=setupCanvas('coin-canvas',640,440),c=a[0],x=a[1],k=keysFor('coinrush'),p,coins,haz,score,combo,time,raf;function reset(){p={x:320,y:220};coins=[];haz=[];score=0;combo=1;time=60;for(var i=0;i<8;i++)spawnCoin();for(var j=0;j<4;j++)spawnHaz();if(raf)raf();raf=rafGame(loop)}function spawnCoin(){coins.push({x:25+Math.random()*590,y:25+Math.random()*390,r:8})}function spawnHaz(){haz.push({x:25+Math.random()*590,y:25+Math.random()*390,r:12,vx:(Math.random()-.5)*100,vy:(Math.random()-.5)*100})}function loop(dt){if(time<=0)return;time-=dt;var dx=(k.ArrowRight||k.KeyD?1:0)-(k.ArrowLeft||k.KeyA?1:0),dy=(k.ArrowDown||k.KeyS?1:0)-(k.ArrowUp||k.KeyW?1:0),l=Math.hypot(dx,dy)||1;p.x=Math.max(12,Math.min(628,p.x+dx/l*230*dt));p.y=Math.max(12,Math.min(428,p.y+dy/l*230*dt));coins.forEach(q=>{if(Math.hypot(q.x-p.x,q.y-p.y)<q.r+12){score+=combo*10;combo=Math.min(10,combo+1);q.x=25+Math.random()*590;q.y=25+Math.random()*390}});haz.forEach(h=>{h.x=(h.x+h.vx*dt+640)%640;h.y=(h.y+h.vy*dt+440)%440;if(Math.hypot(h.x-p.x,h.y-p.y)<h.r+10){score=Math.max(0,score-20);combo=1;h.x=25+Math.random()*590;h.y=25+Math.random()*390}});by('coin-score').textContent=score;by('coin-combo').textContent=combo+'x';by('coin-time').textContent=Math.ceil(time);draw()}function draw(){x.fillStyle='#18231b';x.fillRect(0,0,640,440);x.fillStyle='#f2c94c';coins.forEach(q=>{x.beginPath();x.arc(q.x,q.y,q.r,0,7);x.fill()});x.fillStyle='#d9534f';haz.forEach(h=>{x.beginPath();x.arc(h.x,h.y,h.r,0,7);x.fill()});x.fillStyle='#4f8cff';x.beginPath();x.arc(p.x,p.y,11,0,7);x.fill();if(time<=0){x.fillStyle='#fff';x.font='bold 28px sans-serif';x.textAlign='center';x.fillText('Time! Score '+score,320,220);if(window.saveGameHubScore)window.saveGameHubScore('coinrush',score)}}reset();by('coin-new').onclick=function(){confirmReset(reset)}};
})();
