window.extraGames=window.extraGames||{};window.extraGames.crossy=function(){
  var a=setupCanvas('cr-canvas',560,560),c=a[0],x=a[1],k=keysFor('crossy');
  var W=560,H=560,T=40,COLS=14,ROWS=14;
  var player,lanes,best=0,score=0,raf,dead=false;
  function makeLane(r){if(r<2)return{type:'grass',items:[]};var t=Math.random();var type=t<0.42?'road':t<0.72?'river':t<0.82?'rail':'grass';if(type==='grass')return{type:'grass',items:[]};var dir=Math.random()<.5?1:-1,speed=55+Math.random()*70+r;if(type==='rail')speed=300;return{type:type,dir:dir,speed:speed,items:[],spawnT:0.6+Math.random()*1.6,logLen:2+Math.floor(Math.random()*2)};}
  function reset(){score=0;dead=false;player={x:7,row:0,tx:7,trow:0,moving:false,hopT:1};lanes=[];for(var r=0;r<50;r++)lanes[r]=makeLane(r);by('cr-score').textContent=0;by('cr-best').textContent=best;by('cr-msg').textContent='Arrow keys / WASD to hop. Avoid cars, ride logs, mind the trains.';if(raf)raf();raf=rafGame(loop)}
  function laneAt(r){if(!lanes[r])lanes[r]=makeLane(r);return lanes[r];}
  function tryMove(dc,dr){if(player.moving||dead)return;var nc=Math.round(player.x)+dc,nr=player.row+dr;if(nc<0||nc>=COLS)return;if(nr<0)return;player.tx=nc;player.trow=nr;player.moving=true;player.hopT=0;if(nr>score){score=nr;by('cr-score').textContent=score;if(score>best){best=score;by('cr-best').textContent=best;}}}
  function loop(dt){if(k.ArrowUp||k.KeyW)tryMove(0,1);if(k.ArrowDown||k.KeyS)tryMove(0,-1);if(k.ArrowLeft||k.KeyA)tryMove(-1,0);if(k.ArrowRight||k.KeyD)tryMove(1,0);if(player.moving){player.hopT+=dt/0.13;player.x+=(player.tx-player.x)*0.35;if(player.hopT>=1){player.hopT=1;player.moving=false;player.x=player.tx;player.row=player.trow;}}var viewTop=Math.max(0,player.row-6);for(var r=viewTop;r<viewTop+ROWS+2;r++){var L=laneAt(r);if(L.type==='road'||L.type==='river'){L.spawnT-=dt;if(L.spawnT<=0){if(L.type==='road'){L.spawnT=1.1+Math.random()*1.6;L.items.push({x:L.dir>0?-1.6:COLS+0.5});}else{L.spawnT=1.3+Math.random()*1.1;L.items.push({x:L.dir>0?-3:COLS+0.5,len:L.logLen});}}L.items.forEach(function(it){it.x+=L.dir*L.speed*dt/T;});L.items=L.items.filter(function(it){return it.x>-4&&it.x<COLS+4;});}else if(L.type==='rail'){L.spawnT-=dt;if(L.spawnT<=0){L.spawnT=3.5+Math.random()*2;L.train={x:L.dir>0?-3:COLS+0.5,dir:L.dir};}if(L.train){L.train.x+=L.dir*420*dt/T;if(L.train.x>COLS+4||L.train.x<-4)L.train=null;}}}if(!dead){var pr=player.row,L=laneAt(pr);if(L.type==='road'){L.items.forEach(function(it){if(Math.abs(it.x-player.x)<0.8)die('Squashed!');});}else if(L.type==='river'){var onLog=null;L.items.forEach(function(it){if(player.x>it.x-0.1&&player.x<it.x+it.len+0.1)onLog=it;});if(!onLog)die('Drowned!');else{var d=L.dir*L.speed*dt/T;player.x+=d;player.tx+=d;if(player.x<-0.3||player.x>COLS-0.7)die('Swept away!');}}else if(L.type==='rail'){if(L.train&&Math.abs(L.train.x-player.x)<1.2)die('Hit by train!');}if(pr<viewTop-1)die('Fell off the bottom!');}draw(viewTop)}
  function die(msg){dead=true;by('cr-msg').textContent=msg+' Score '+score+'. Press New run.';}
  function draw(viewTop){x.fillStyle='#7ac74f';x.fillRect(0,0,W,H);for(var r=0;r<ROWS+2;r++){var rr=viewTop+r;if(rr<0)continue;var L=laneAt(rr);var sy=H-(r+1)*T;if(L.type==='grass'){x.fillStyle=(rr%2)?'#7ac74f':'#6fb846';x.fillRect(0,sy,W,T);}else if(L.type==='road'){x.fillStyle='#3a3f44';x.fillRect(0,sy,W,T);x.strokeStyle='#6a6f74';x.lineWidth=2;for(var i=0;i<COLS;i++){x.beginPath();x.moveTo(i*T+T/2,sy);x.lineTo(i*T+T/2,sy+T);x.stroke();}}else if(L.type==='river'){x.fillStyle='#3a6ea5';x.fillRect(0,sy,W,T);}else if(L.type==='rail'){x.fillStyle='#5a4f44';x.fillRect(0,sy,W,T);x.fillStyle='#2a2520';x.fillRect(0,sy+T/2-3,W,6);}if(L.type==='road'){L.items.forEach(function(it){x.fillStyle='#d9534f';x.fillRect(it.x*T,sy+6,1.6*T,T-12);x.fillStyle='#222';x.fillRect(it.x*T+4,sy+T-12,8,6);});}if(L.type==='river'){L.items.forEach(function(it){x.fillStyle='#8a5a2a';x.fillRect(it.x*T,sy+4,it.len*T,T-8);});}if(L.type==='rail'&&L.train){x.fillStyle='#2a2a2a';x.fillRect(L.train.x*T,sy+4,2.4*T,T-12);x.fillStyle='#f2c94c';x.fillRect(L.train.x*T+2.2*T,sy+8,8,8);}}var srow=player.row-viewTop;var px=player.x*T+(T-26)/2;var py=H-(srow+1)*T+(T-26)/2-Math.sin(player.hopT*Math.PI)*12;x.fillStyle='#f2c94c';x.fillRect(px,py,26,26);x.fillStyle='#222';x.fillRect(px+5,py+7,5,5);x.fillRect(px+14,py+7,5,5);if(dead){x.fillStyle='rgba(0,0,0,.55)';x.fillRect(0,0,W,H);x.fillStyle='#fff';x.font='bold 26px sans-serif';x.textAlign='center';x.fillText('Game Over',W/2,H/2);}}
  by('cr-new').onclick=function(){confirmReset(reset);};reset();
};
