(function(){
window.extraGames=window.extraGames||{};
window.extraGames.dodge=function(){
function by(id){return document.getElementById(id)}
function setup(id,w,h){var c=by(id);if(!c)return null;c.width=w;c.height=h;return[c,c.getContext('2d')]}
function keys(){var k={};document.addEventListener('keydown',function(e){k[e.code]=true});document.addEventListener('keyup',function(e){k[e.code]=false});return k}
var a=setup('dodge-canvas',640,440);if(!a)return;var c=a[0],x=a[1],k=keys(),p,obs,score,best=0,raf;
function stop(){if(raf){cancelAnimationFrame(raf);raf=0}}
function reset(){stop();p={x:320,y:220};obs=[];score=0;by('dodge-score').textContent=0;by('dodge-msg').textContent='WASD / arrows to move. Avoid the incoming circles.';var last=performance.now();function loop(t){var dt=Math.min(.035,(t-last)/1000);last=t;var dx=(k.ArrowRight||k.KeyD?1:0)-(k.ArrowLeft||k.KeyA?1:0),dy=(k.ArrowDown||k.KeyS?1:0)-(k.ArrowUp||k.KeyW?1:0),len=Math.hypot(dx,dy)||1;p.x=Math.max(12,Math.min(628,p.x+dx/len*260*dt));p.y=Math.max(12,Math.min(428,p.y+dy/len*260*dt));score+=dt*10;if(Math.random()<dt*(1+score/500))spawn();obs.forEach(function(o){o.x+=o.vx*dt;o.y+=o.vy*dt});obs=obs.filter(function(o){return o.x>-40&&o.x<680&&o.y>-40&&o.y<480});if(obs.some(function(o){return Math.hypot(o.x-p.x,o.y-p.y)<o.r+10})){best=Math.max(best,Math.floor(score));by('dodge-best').textContent=best;by('dodge-msg').textContent='Hit! Score '+Math.floor(score);if(window.saveGameHubScore)window.saveGameHubScore('dodge',Math.floor(score));return}by('dodge-score').textContent=Math.floor(score);draw();raf=requestAnimationFrame(loop)}function spawn(){var side=Math.floor(Math.random()*4),ox=side===0?0:side===1?640:Math.random()*640,oy=side===2?0:side===3?440:Math.random()*440,dx=p.x-ox,dy=p.y-oy,len=Math.hypot(dx,dy)||1,sp=130+score;obs.push({x:ox,y:oy,r:8+Math.random()*10,vx:dx/len*sp,vy:dy/len*sp})}function draw(){x.fillStyle='#101114';x.fillRect(0,0,640,440);x.fillStyle='#d9534f';obs.forEach(function(o){x.beginPath();x.arc(o.x,o.y,o.r,0,Math.PI*2);x.fill()});x.fillStyle='#4f8cff';x.beginPath();x.arc(p.x,p.y,10,0,Math.PI*2);x.fill()}raf=requestAnimationFrame(loop)}reset();by('dodge-new').onclick=reset};
})();
