window.extraGames=window.extraGames||{};window.extraGames.paperio=function(){
var a=setupCanvas('pi-canvas',560,560),c=a[0],x=a[1],k=keysFor('paperio');var N=40,CS=14,raf,over=false,best=0;var grid,trail,snakes;
function reset(){grid=new Array(N*N).fill(0);trail=new Array(N*N).fill(0);snakes=[];makeSnake(1,4,Math.floor(N/2),1,0,'#4f9cf0');makeSnake(2,N-5,Math.floor(N/2),-1,0,'#f07050');makeSnake(3,Math.floor(N/2),4,0,1,'#6fae4a');makeSnake(4,Math.floor(N/2),N-5,0,-1,'#e8c86e');snakes.forEach(function(s){for(var dy=-1;dy<=1;dy++)for(var dx=-1;dx<=1;dx++)grid[((s.y+dy+N)%N)*N+((s.x+dx+N)%N)]=s.id;});over=false;by('pi-pct').textContent=0;by('pi-best').textContent=best;by('pi-msg').textContent='WASD / arrows to move. Leave your zone, loop back to claim land.';if(raf)raf();raf=rafGame(loop)}
function makeSnake(id,x,y,dx,dy,col){snakes.push({id:id,x:x,y:y,fx:x+0.5,fy:y+0.5,dx:dx,dy:dy,nx:dx,ny:dy,col:col,alive:true,trail:[],step:0});}function idx(cx,cy){return cy*N+cx;}
function onCell(s,cx,cy){var i=idx(cx,cy);if(trail[i]!==0){if(trail[i]===s.id){kill(s);return;}var os=snakes.find(function(z){return z.id===trail[i];});if(os)kill(os);}if(grid[i]===s.id){if(s.trail.length>0)capture(s);}else{trail[i]=s.id;s.trail.push(i);}}
function capture(s){s.trail.forEach(function(i){grid[i]=s.id;trail[i]=0;});s.trail=[];var outside=new Array(N*N).fill(false),q=[];for(var i=0;i<N*N;i++){if(grid[i]!==s.id){var yy=i/N|0,xx=i%N;if(xx===0||yy===0||xx===N-1||yy===N-1){outside[i]=true;q.push(i);}}}while(q.length){var i=q.pop(),yy=i/N|0,xx=i%N,nb=[[xx-1,yy],[xx+1,yy],[xx,yy-1],[xx,yy+1]];for(var m=0;m<nb.length;m++){var nx=nb[m][0],ny=nb[m][1];if(nx<0||ny<0||nx>=N||ny>=N)continue;var ni=ny*N+nx;if(!outside[ni]&&grid[ni]!==s.id){outside[ni]=true;q.push(ni);}}}for(var i=0;i<N*N;i++)if(grid[i]!==s.id&&!outside[i])grid[i]=s.id;if(s.id===1){var pct=Math.round(count(1)/(N*N)*100);by('pi-pct').textContent=pct;if(pct>best){best=pct;by('pi-best').textContent=best;}}}
function count(id){var n=0;for(var i=0;i<N*N;i++)if(grid[i]===id)n++;return n;}function kill(s){if(!s.alive)return;s.alive=false;s.trail.forEach(function(i){trail[i]=0;});s.trail=[];if(s.id===1){over=true;var pct=Math.round(count(1)/(N*N)*100);if(pct>best){best=pct;by('pi-best').textContent=best;}by('pi-msg').textContent='You got cut off! You held '+pct+'% of the map.';}}
function botAI(s){var ax=s.x+s.dx,ay=s.y+s.dy,bad=ax<0||ay<0||ax>=N||ay>=N||trail[idx(ax,ay)]!==0;if(bad){var opts=s.dx!==0?[[0,1],[0,-1]]:[[1,0],[-1,0]],ch=opts.find(function(o){var nx2=s.x+o[0],ny2=s.y+o[1];return nx2>=0&&ny2>=0&&nx2<N&&ny2<N&&trail[idx(nx2,ny2)]===0;});if(ch){s.nx=ch[0];s.ny=ch[1];}else{s.nx=-s.dx;s.ny=-s.dy;}}}
function loop(dt){if(over){draw();return;}var p=snakes[0];if(k.ArrowUp||k.KeyW){if(p.dy!==1){p.nx=0;p.ny=-1;}}if(k.ArrowDown||k.KeyS){if(p.dy!==-1){p.nx=0;p.ny=1;}}if(k.ArrowLeft||k.KeyA){if(p.dx!==1){p.nx=-1;p.ny=0;}}if(k.ArrowRight||k.KeyD){if(p.dx!==-1){p.nx=1;p.ny=0;}}var v=7;snakes.forEach(function(s){if(!s.alive)return;if(s.id!==1)botAI(s);if(!(s.nx===-s.dx&&s.ny===-s.dy)){s.dx=s.nx;s.dy=s.ny;}s.fx+=s.dx*v*dt;s.fy+=s.dy*v*dt;var cx=Math.floor(s.fx),cy=Math.floor(s.fy);if(cx!==s.x||cy!==s.y){if(cx<0||cy<0||cx>=N||cy>=N){kill(s);return;}s.x=cx;s.y=cy;s.fx=cx+0.5;s.fy=cy+0.5;onCell(s,cx,cy);}});if(!over)by('pi-pct').textContent=Math.round(count(1)/(N*N)*100);draw();}
function draw(){x.fillStyle='#0e1422';x.fillRect(0,0,N*CS,N*CS);for(var y=0;y<N;y++)for(var xx=0;xx<N;xx++){var i=y*N+xx,o=grid[i];if(o!==0){x.fillStyle=snakeColor(o);x.fillRect(xx*CS,y*CS,CS,CS);}if(trail[i]!==0){x.fillStyle=snakeColor(trail[i]);x.globalAlpha=0.6;x.fillRect(xx*CS,y*CS,CS,CS);x.globalAlpha=1;}}snakes.forEach(function(s){if(!s.alive)return;x.fillStyle=s.col;x.fillRect(s.x*CS,s.y*CS,CS,CS);x.fillStyle='#fff';x.fillRect(s.x*CS+CS/2-1,s.y*CS+CS/2-1,3,3);});if(over){x.fillStyle='rgba(0,0,0,.6)';x.fillRect(0,0,N*CS,N*CS);x.fillStyle='#fff';x.font='bold 22px sans-serif';x.textAlign='center';x.fillText('Game Over',N*CS/2,N*CS/2-10);x.font='14px sans-serif';x.fillText(by('pi-msg').textContent,N*CS/2,N*CS/2+16);}}
function snakeColor(id){var m={1:'#4f9cf0',2:'#f07050',3:'#6fae4a',4:'#e8c86e'};return m[id]||'#888';}by('pi-new').onclick=function(){confirmReset(reset);};reset();};
