(function(){
  window.extraGames=window.extraGames||{};
  function by(id){return document.getElementById(id)}
  function setupCanvas(id,w,h){var c=by(id);if(!c)return [null,null];c.width=w;c.height=h;return [c,c.getContext('2d')]}
  function keysFor(view){var k={};document.addEventListener('keydown',function(e){var v=by('view-'+view);if(!v||!v.classList.contains('active'))return;k[e.code]=true;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space','KeyW','KeyA','KeyS','KeyD','Enter','KeyF'].indexOf(e.code)>=0)e.preventDefault();});document.addEventListener('keyup',function(e){k[e.code]=false});return k}
  function rafGame(loop){var id=0,last=performance.now();function f(t){var dt=Math.min(.035,(t-last)/1000);last=t;loop(dt,t);id=requestAnimationFrame(f)}id=requestAnimationFrame(f);return function(){cancelAnimationFrame(id)}}
  var confirmReset=window.confirmReset||function(fn){fn()};
  window.extraGames.racing=function(){var a=setupCanvas('racing-canvas',640,440),c=a[0],x=a[1],k=keysFor('racing'),car,lap=1,t=0,done=false,off=0,boost=0,raf;
    function reset(){car={x:320,y:360,a:-Math.PI/2,v:0};lap=1;t=0;done=false;off=0;boost=0;by('race-lap').textContent=1;by('race-time').textContent='0.0';by('racing-msg').textContent='WASD / arrows to drive · Space for boost';if(raf)raf();raf=rafGame(function(dt){if(done)return;t+=dt;var turn=(k.ArrowLeft||k.KeyA?-1:0)+(k.ArrowRight||k.KeyD?1:0);var gas=(k.ArrowUp||k.KeyW?1:0)-((k.ArrowDown||k.KeyS ? .6 : 0));if(k.Space&&boost<=0){boost=.7}if(boost>0){boost-=dt;gas=1.8}car.v+=gas*300*dt;car.v*=Math.pow(.985,dt*60);car.v=Math.max(-90,Math.min(290,car.v));car.a+=turn*2.7*dt*(.4+Math.abs(car.v)/220);car.x+=Math.cos(car.a)*car.v*dt;car.y+=Math.sin(car.a)*car.v*dt;var cx=320+Math.cos(off)*180,cy=220+Math.sin(off)*130;var dx=car.x-cx,dy=car.y-cy;var inside=(dx*dx)/(250*250)+(dy*dy)/(180*180)<1;if(!inside)car.v*=.96;if(Math.hypot(car.x-320,car.y-360)<35&&car.v>80){lap++;by('race-lap').textContent=Math.min(lap,3);car.x=320;car.y=360;car.a=-Math.PI/2;if(lap>3){done=true;by('racing-msg').textContent='🏁 Finished in '+t.toFixed(1)+' seconds!';if(window.saveGameHubScore)window.saveGameHubScore('racing',Math.max(0,Math.round(10000-t*100)))}}by('race-time').textContent=t.toFixed(1);draw()});}
    function draw(){x.fillStyle='#15221a';x.fillRect(0,0,640,440);x.fillStyle='#5b5145';x.fillRect(45,35,550,370);x.fillStyle='#20252a';x.beginPath();x.ellipse(320,220,250,180,0,0,Math.PI*2);x.fill();x.fillStyle='#15221a';x.beginPath();x.ellipse(320,220,155,95,0,0,Math.PI*2);x.fill();x.strokeStyle='#f4d35e';x.setLineDash([14,12]);x.lineWidth=3;x.beginPath();x.ellipse(320,220,202,137,0,0,Math.PI*2);x.stroke();x.setLineDash([]);x.fillStyle='#fff';x.fillRect(285,340,70,8);x.save();x.translate(car.x,car.y);x.rotate(car.a);x.fillStyle=boost>0?'#f7c948':'#4f8cff';x.fillRect(-16,-9,32,18);x.fillStyle='#111';x.fillRect(4,-6,8,12);x.restore()}
    reset();by('racing-new').onclick=function(){confirmReset(reset)};
  };
})();
