window.extraGames=window.extraGames||{};window.extraGames.snakeio=function(){
function by(id){return document.getElementById(id)}function setup(id,w,h){var c=by(id);if(!c)return null;c.width=w;c.height=h;return[c,c.getContext('2d')]}function keys(){var k={};document.addEventListener('keydown',function(e){var v=by('view-snakeio');if(!v||!v.classList.contains('active'))return;k[e.code]=true});document.addEventListener('keyup',function(e){k[e.code]=false});return k}
var a=setup('si-canvas',560,560);if(!a)return;var c=a[0],x=a[1],k=keys(),W=560,H=560,raf=0,over=false,best=0,player,bots,pellets,grace,autoOrbit,spawnTimer,last=0;var mouse={x:280,y:280,active:false,down:false};
function randColor(){return'hsl('+Math.floor(Math.random()*360)+',65%,58%)'}function mk(px,py,ang,col,len){return{x:px,y:py,ang:ang,col:col,segs:[{x:px,y:py}],len:len,boostT:0,alive:true}}
function stop(){if(raf){cancelAnimationFrame(raf);raf=0}}
function safeBotSpawn(){for(var n=0;n<40;n++){var px=70+Math.random()*420,py=70+Math.random()*420;if(Math.hypot(px-player.x,py-player.y)>170)return[px,py]}return[500,500]}
function reset(){stop();over=false;grace=2.5;autoOrbit=true;spawnTimer=1.5;last=0;player=mk(280,280,0,'#4f9cf0',12);bots=[];pellets=[];for(var i=0;i<24;i++)spawnPellet();by('si-len').textContent=player.len;by('si-best').textContent=best;by('si-msg').textContent='Starting safely… Mouse or WASD to steer · Space/click to boost.';raf=requestAnimationFrame(loop)}
function spawnPellet(){pellets.push({x:25+Math.random()*(W-50),y:25+Math.random()*(H-50),r:4,col:randColor()})}
function spawnPelletAt(px,py){pellets.push({x:px,y:py,r:4,col:randColor()})}
function moveSnake(s,dt,boosting){if(!s.alive)return;var v=120*(boosting?1.8:1);if(boosting&&s.len>3){s.boostT-=dt;if(s.boostT<=0){s.boostT=.12;s.len--;var tail=s.segs[s.segs.length-1];if(tail)spawnPelletAt(tail.x,tail.y)}}s.x+=Math.cos(s.ang)*v*dt;s.y+=Math.sin(s.ang)*v*dt;if(s.x<12||s.x>W-12||s.y<12||s.y>H-12){kill(s);return}s.segs.unshift({x:s.x,y:s.y});while(s.segs.length>s.len)s.segs.pop()}
function botSteer(b,dt){var target=null,bd=1e9;for(var i=0;i<pellets.length;i++){var d=Math.hypot(pellets[i].x-b.x,pellets[i].y-b.y);if(d<bd){bd=d;target=pellets[i]}}if(target){var t=Math.atan2(target.y-b.y,target.x-b.x),dd=((t-b.ang+Math.PI*3)%(Math.PI*2))-Math.PI;b.ang+=Math.sign(dd)*Math.min(Math.abs(dd),2.2*dt)}if(b.x<45)b.ang=0;if(b.x>W-45)b.ang=Math.PI;if(b.y<45)b.ang=Math.PI/2;if(b.y>H-45)b.ang=-Math.PI/2}
function kill(s){if(!s.alive)return;s.alive=false;for(var i=0;i<s.segs.length;i+=3)spawnPelletAt(s.segs[i].x,s.segs[i].y);if(s===player){over=true;best=Math.max(best,player.len);by('si-best').textContent=best;by('si-msg').textContent='You crashed! Length '+player.len+'. Press New game.';if(window.saveGameHubScore)window.saveGameHubScore('snakeio',best);stop()}}
function checkCollisions(){if(grace>0)return;var all=[player].concat(bots);for(var i=0;i<all.length;i++){var s=all[i];if(!s.alive)continue;for(var j=0;j<all.length;j++){var b=all[j];if(!b.alive)continue;var start=s===b?7:3;for(var q=start;q<b.segs.length;q++){if(Math.hypot(s.x-b.segs[q].x,s.y-b.segs[q].y)<9){kill(s);break}}if(!s.alive)break}}}
function loop(t){if(!last)last=t;var dt=Math.min(.035,(t-last)/1000);last=t;if(over){draw();return}if(grace>0){grace-=dt;by('si-msg').textContent='Starting safely… '+Math.ceil(grace)+'s'}if(autoOrbit&&!mouse.active&&!k.ArrowLeft&&!k.ArrowRight&&!k.KeyA&&!k.KeyD)player.ang+=1.1*dt;if(mouse.active||k.ArrowLeft||k.ArrowRight||k.KeyA||k.KeyD)autoOrbit=false;if(k.ArrowLeft||k.KeyA)player.ang-=3.5*dt;if(k.ArrowRight||k.KeyD)player.ang+=3.5*dt;if(mouse.active){var target=Math.atan2(mouse.y-player.y,mouse.x-player.x),dd=((target-player.ang+Math.PI*3)%(Math.PI*2))-Math.PI;player.ang+=Math.sign(dd)*Math.min(Math.abs(dd),4*dt)}var boosting=k.Space||mouse.down;k.Space=false;moveSnake(player,dt,boosting);spawnTimer-=dt;if(spawnTimer<=0&&bots.length<4){var pos=safeBotSpawn();bots.push(mk(pos[0],pos[1],Math.random()*Math.PI*2,randColor(),10));spawnTimer=2.5+Math.random()*2}bots.forEach(function(b){botSteer(b,dt);moveSnake(b,dt,false)});[player].concat(bots).forEach(function(s){if(!s.alive)return;for(var i=pellets.length-1;i>=0;i--)if(Math.hypot(s.x-pellets[i].x,s.y-pellets[i].y)<pellets[i].r+9){s.len+=3;pellets.splice(i,1)}});while(pellets.length<24)spawnPellet();checkCollisions();bots=bots.filter(function(b){return b.alive});by('si-len').textContent=player.len;draw();raf=requestAnimationFrame(loop)}
function draw(){x.fillStyle='#0e1422';x.fillRect(0,0,W,H);x.strokeStyle='rgba(255,255,255,.05)';x.lineWidth=1;for(var g=0;g<=W;g+=40){x.beginPath();x.moveTo(g,0);x.lineTo(g,H);x.stroke();x.beginPath();x.moveTo(0,g);x.lineTo(W,g);x.stroke()}pellets.forEach(function(p){x.fillStyle=p.col;x.beginPath();x.arc(p.x,p.y,p.r,0,7);x.fill()});function ds(s){for(var i=s.segs.length-1;i>=0;i--){var z=s.segs[i];x.fillStyle=s.col;x.beginPath();x.arc(z.x,z.y,7-i*.02,0,7);x.fill()}if(s.alive){x.fillStyle='#fff';x.beginPath();x.arc(s.x+Math.cos(s.ang-.4)*4,s.y+Math.sin(s.ang-.4)*4,2.5,0,7);x.fill();x.beginPath();x.arc(s.x+Math.cos(s.ang+.4)*4,s.y+Math.sin(s.ang+.4)*4,2.5,0,7);x.fill()}}ds(player);bots.forEach(ds)}
c.addEventListener('mousemove',function(e){var r=c.getBoundingClientRect();mouse.x=(e.clientX-r.left)*W/r.width;mouse.y=(e.clientY-r.top)*H/r.height;mouse.active=true});c.addEventListener('mouseleave',function(){mouse.active=false});c.addEventListener('mousedown',function(){mouse.down=true});window.addEventListener('mouseup',function(){mouse.down=false});c.addEventListener('touchmove',function(e){var q=e.touches[0],r=c.getBoundingClientRect();mouse.x=(q.clientX-r.left)*W/r.width;mouse.y=(q.clientY-r.top)*H/r.height;mouse.active=true;e.preventDefault()},{passive:false});c.addEventListener('touchstart',function(e){mouse.down=true},{passive:false});c.addEventListener('touchend',function(){mouse.down=false;mouse.active=false});by('si-new').onclick=function(){reset()};reset()};
