window.extraGames=window.extraGames||{};window.extraGames.snakeio=function(){
var a=setupCanvas('si-canvas',560,560),c=a[0],x=a[1],k=keysFor('snakeio');var W=560,H=560,raf,over=false,best=0;var player,bots,pellets,grace=0,autoOrbit=true;var mouse={x:280,y:280,active:false,down:false};function randColor(){return 'hsl('+Math.floor(Math.random()*360)+',65%,58%)';}
function reset(){over=false;grace=0.8;autoOrbit=true;player=mk(280,280,0,'#4f9cf0',12);bots=[];pellets=[];for(var i=0;i<40;i++)spawnPellet();var bsp=[[90,90,0.6],[470,90,2.4],[470,470,3.9],[90,470,5.4]];for(var i=0;i<4;i++){var s=bsp[i];bots.push(mk(s[0],s[1],s[2],randColor(),10));}by('si-len').textContent=player.segs.length;by('si-best').textContent=best;by('si-msg').textContent='Mouse or WASD to steer · Space/click to boost.';if(raf)raf();raf=rafGame(loop);}
function mk(x,y,ang,col,len){return{x:x,y:y,ang:ang,col:col,segs:[{x:x,y:y}],len:len,boostT:0,alive:true};}function spawnPellet(){pellets.push({x:20+Math.random()*(W-40),y:20+Math.random()*(H-40),r:4,col:randColor()});}function spawnPelletAt(px,py){pellets.push({x:px,y:py,r:4,col:randColor()});}
function moveSnake(s,dt,boosting){if(!s.alive)return;var v=120*(boosting?1.8:1);if(boosting&&s.len>3){s.boostT-=dt;if(s.boostT<=0){s.boostT=0.12;s.len-=1;var t=s.segs[s.segs.length-1];if(t)spawnPelletAt(t.x,t.y);}}s.x+=Math.cos(s.ang)*v*dt;s.y+=Math.sin(s.ang)*v*dt;if(s.x<8||s.x>W-8||s.y<8||s.y>H-8){kill(s);return;}s.segs.unshift({x:s.x,y:s.y});while(s.segs.length>s.len)s.segs.pop();}
function botSteer(b){var best=null,bd=1e9;for(var i=0;i<pellets.length;i++){var d=Math.hypot(pellets[i].x-b.x,pellets[i].y-b.y);if(d<bd){bd=d;best=pellets[i];}}if(best){var t=Math.atan2(best.y-b.y,best.x-b.x),dd=((t-b.ang+Math.PI*3)%(Math.PI*2))-Math.PI;b.ang+=Math.sign(dd)*Math.min(Math.abs(dd),2.5*0.016);}if(b.x<40)b.ang=0;if(b.x>W-40)b.ang=Math.PI;if(b.y<40)b.ang=Math.PI/2;if(b.y>H-40)b.ang=-Math.PI/2;}
function checkCollisions(){var all=[player].concat(bots);all.forEach(function(a){if(!a.alive)return;if(a===player&&grace>0)return;all.forEach(function(b){if(!b.alive)return;for(var i=4;i<b.segs.length;i++)if(Math.hypot(a.x-b.segs[i].x,a.y-b.segs[i].y)<8){kill(a);return;}});});}
function kill(s){if(!s.alive)return;s.alive=false;for(var i=0;i<s.segs.length;i+=2)spawnPelletAt(s.segs[i].x,s.segs[i].y);if(s===player){over=true;if(player.len>best){best=player.len;by('si-best').textContent=best;}by('si-msg').textContent='You crashed! Length '+player.len+'. Press New game.';}}
function loop(dt){if(over){draw();return;}if(grace>0)grace-=dt;if(autoOrbit&&!mouse.active&&!k.ArrowLeft&&!k.ArrowRight&&!k.KeyA&&!k.KeyD)player.ang+=1.4*dt;if(mouse.active||k.ArrowLeft||k.ArrowRight||k.KeyA||k.KeyD)autoOrbit=false;if(k.ArrowLeft||k.KeyA)player.ang-=3.5*dt;if(k.ArrowRight||k.KeyD)player.ang+=3.5*dt;if(mouse.active){var t=Math.atan2(mouse.y-player.y,mouse.x-player.x),dd=((t-player.ang+Math.PI*3)%(Math.PI*2))-Math.PI;player.ang+=Math.sign(dd)*Math.min(Math.abs(dd),4*dt);}var boosting=(k.Space||mouse.down);moveSnake(player,dt,boosting);bots.forEach(function(b){botSteer(b);moveSnake(b,dt,false);});[player].concat(bots).forEach(function(s){if(!s.alive)return;for(var i=pellets.length-1;i>=0;i--)if(Math.hypot(s.x-pellets[i].x,s.y-pellets[i].y)<pellets[i].r+8){s.len+=3;spawnPelletAt(pellets[i].x,pellets[i].y);pellets.splice(i,1);}});while(pellets.length<40)spawnPellet();checkCollisions();bots=bots.filter(function(b){return b.alive;});while(bots.length<4){var ang=Math.random()*6.28;bots.push(mk(100+Math.random()*360,100+Math.random()*360,ang,randColor(),10));}by('si-len').textContent=player.segs.length;draw();}
function draw(){x.fillStyle='#0e1422';x.fillRect(0,0,W,H);x.strokeStyle='rgba(255,255,255,.05)';x.lineWidth=1;for(var g=0;g<=W;g+=40){x.beginPath();x.moveTo(g,0);x.lineTo(g,H);x.stroke();x.beginPath();x.moveTo(0,g);x.lineTo(W,g);x.stroke();}pellets.forEach(function(p){x.fillStyle=p.col;x.beginPath();x.arc(p.x,p.y,p.r,0,7);x.fill();});function drawSnake(s){for(var i=s.segs.length-1;i>=0;i--){var seg=s.segs[i];x.fillStyle=s.col;x.beginPath();x.arc(seg.x,seg.y,7-i*0.02,0,7);x.fill();}if(s.alive){x.fillStyle='#fff';x.beginPath();x.arc(s.x+Math.cos(s.ang-0.4)*4,s.y+Math.sin(s.ang-0.4)*4,2.5,0,7);x.fill();x.beginPath();x.arc(s.x+Math.cos(s.ang+0.4)*4,s.y+Math.sin(s.ang+0.4)*4,2.5,0,7);x.fill();}}drawSnake(player);bots.forEach(drawSnake);if(over){x.fillStyle='rgba(0,0,0,.6)';x.fillRect(0,0,W,H);x.fillStyle='#fff';x.font='bold 24px sans-serif';x.textAlign='center';x.fillText('Game Over',W/2,H/2);}}
c.addEventListener('mousemove',function(e){var r=c.getBoundingClientRect();mouse.x=(e.clientX-r.left)*W/r.width;mouse.y=(e.clientY-r.top)*H/r.height;mouse.active=true;});c.addEventListener('mouseleave',function(){mouse.active=false;});c.addEventListener('mousedown',function(){mouse.down=true;});window.addEventListener('mouseup',function(){mouse.down=false;});c.addEventListener('touchmove',function(e){var t=e.touches[0],r=c.getBoundingClientRect();mouse.x=(t.clientX-r.left)*W/r.width;mouse.y=(t.clientY-r.top)*H/r.height;mouse.active=true;e.preventDefault();},{passive:false});c.addEventListener('touchstart',function(e){mouse.down=true;},{passive:false});c.addEventListener('touchend',function(){mouse.down=false;mouse.active=false;});by('si-new').onclick=function(){confirmReset(reset);};reset();};
