(function(){
  window.extraGames=window.extraGames||{};
  function by(id){return document.getElementById(id)}
  function setupCanvas(id,w,h){var c=by(id);if(!c)return [null,null];c.width=w;c.height=h;return [c,c.getContext('2d')]}
  function keysFor(view){var k={};document.addEventListener('keydown',function(e){var v=by('view-'+view);if(!v||!v.classList.contains('active'))return;k[e.code]=true;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space','KeyW','KeyA','KeyS','KeyD','Enter','KeyF'].indexOf(e.code)>=0)e.preventDefault();});document.addEventListener('keyup',function(e){k[e.code]=false});return k}
  function rafGame(loop){var id=0,last=performance.now();function f(t){var dt=Math.min(.035,(t-last)/1000);last=t;loop(dt,t);id=requestAnimationFrame(f)}id=requestAnimationFrame(f);return function(){cancelAnimationFrame(id)}}
  var confirmReset=window.confirmReset||function(fn){fn()};
  window.extraGames.tetris=function(){var c=by('tetris-canvas'),x=c.getContext('2d'),k=keysFor('tetris'),grid,piece,score,lines,level,drop,raf,shapes=[[[1,1,1,1]],[[1,1],[1,1]],[[0,1,0],[1,1,1]],[[1,0,0],[1,1,1]],[[0,0,1],[1,1,1]],[[1,1,0],[0,1,1]],[[0,1,1],[1,1,0]]];function reset(){grid=Array.from({length:20},()=>Array(10).fill(0));score=lines=0;level=1;drop=0;piece=null;spawn();hud();if(raf)raf();raf=rafGame(loop)}function spawn(){var sh=shapes[Math.floor(Math.random()*shapes.length)];piece={s:sh.map(r=>r.slice()),x:3,y:0};if(collide(piece)){by('tet-msg').textContent='Game over — score '+score;if(window.saveGameHubScore)window.saveGameHubScore('tetris',score);piece=null}}function collide(p,ox=0,oy=0,rot=p.s){for(var r=0;r<rot.length;r++)for(var q=0;q<rot[r].length;q++)if(rot[r][q]){var X=p.x+q+ox,Y=p.y+r+oy;if(X<0||X>=10||Y>=20||Y>=0&&grid[Y][X])return true}return false}function rotate(){if(!piece)return;var s=piece.s,n=s.length,m=s[0].length,r=Array.from({length:m},(_,i)=>Array.from({length:n},(_,j)=>s[n-1-j][i]));if(!collide(piece,0,0,r))piece.s=r}function lock(){piece.s.forEach((r,rr)=>r.forEach((v,cc)=>{if(v)grid[piece.y+rr][piece.x+cc]=1}));for(var r=19;r>=0;r--)if(grid[r].every(Boolean)){grid.splice(r,1);grid.unshift(Array(10).fill(0));lines++;score+=100*level;r++}level=1+Math.floor(lines/10);spawn();hud()}function loop(dt){if(!piece)return;drop+=dt;if(k.ArrowLeft){k.ArrowLeft=false;if(!collide(piece,-1))piece.x--}if(k.ArrowRight){k.ArrowRight=false;if(!collide(piece,1))piece.x++}if(k.ArrowUp){k.ArrowUp=false;rotate()}if(k.Space){k.Space=false;while(!collide(piece,0,1))piece.y++;lock()}if(drop>Math.max(.12,.8-level*.06)){drop=0;if(!collide(piece,0,1))piece.y++;else lock()}draw()}function hud(){by('tet-score').textContent=score;by('tet-lines').textContent=lines;by('tet-level').textContent=level}function draw(){x.fillStyle='#101114';x.fillRect(0,0,300,600);x.strokeStyle='#333';for(var i=0;i<=10;i++){x.beginPath();x.moveTo(i*30,0);x.lineTo(i*30,600);x.stroke()}for(var r=0;r<=20;r++){x.beginPath();x.moveTo(0,r*30);x.lineTo(300,r*30);x.stroke()}x.fillStyle='#5b8def';grid.forEach((row,r)=>row.forEach((v,c)=>{if(v)x.fillRect(c*30+2,r*30+2,26,26)}));if(piece){x.fillStyle='#f2c94c';piece.s.forEach((row,r)=>row.forEach((v,c)=>{if(v)x.fillRect((piece.x+c)*30+2,(piece.y+r)*30+2,26,26)}))}}reset();by('tet-new').onclick=function(){confirmReset(reset)}};
})();
